### ISSUE TITLE
Add Vim 8 Terminal support

### ISSUE THREAD

**Issue by bahlo** [sebdah/vim-delve#25]
Is this possible? Would increase usability in Vim 8 by much.

**Comment by sebdah** [comment]
Hmm, I wasn't even aware that there was a terminal in Vim. Is this the one you mean? http://vimhelp.appspot.com/terminal.txt.html

I'm using only Neovim, so I'm not really up-to-date with the latest changes in Vim unfortunately.

Would be happy to do some better integration with Vim, the current implementation relying on third party support isn't ideal.

Got a little scared by this section in the help for the Vim 8 terminal:

> WARNING: THIS IS ONLY PARTLY IMPLEMENTED, ANYTHING CAN STILL CHANGE
