### ISSUE TITLE
Plz add a "Getting started" section to readme

### ISSUE THREAD

**Issue by GodloveD** [sebdah/vim-delve#27]
This project seems cool, but after installing neovim and adding the package, I don't really know how to get started using it.  If I use `nvim` to open the source file containing `main()` and try to execute `DlvToggleBreakpoint` I just get:

```
E492: Not an editor command: DlvToggleBreakpoint
``` 

I'm sure it is probably very simple, but so am I!  Can I get some hints.  😄

**Comment by fuweid** [comment]
Hi @GodloveD , 

I didn't reproduce your issue. Could you mind to provide your env information? for example, the version of nvim.

BTW, what kind of the `Get Started` do you want? :smile:  I think that the gif in the `README.md` is good enough. You can point out what you want. 😃

**Comment by sebdah** [comment]
@GodloveD It seems like vim-delve was not properly installed. What steps did you take to install it?

**Comment by GodloveD** [comment]
@sebdah I just followed the installation instructions [here](https://github.com/sebdah/vim-delve#installation).  Nothing fancy.  I installed nvim via `apt`.

**Comment by sebdah** [comment]
Did you use a package manager for neovim (like plug or pathogen) to install
vim-delve?

**Comment by GodloveD** [comment]
Hi @sebdah!  Yes I used plug.

**Comment by sebdah** [comment]
I see, is there no error when you run `:PlugInstall`? Basically the vim-delve plugin is not installed in your Neovim setup. So I'd guess that either Plug is misconfigured or the installation fails somehow.

Maybe you could try removing the plugin and install it again and keep a close eye on the installation. After Plug is done installing you could see more details about how the installation went (I think you'd press `D`).
