### ISSUE TITLE
(Possibly) Need an example of passing go build flags to delve

### ISSUE THREAD

**Issue by robinbryce** [sebdah/vim-delve#28]
MacOS 10.13.5 (tmux and iterm-2), dlv 1.0.0-rc.1, neovim  v0.3.1-36-gb006771, vim-delv commit 2f2a61e3649bc63a53a50

Using DlvDebug -- inferior args, my program launches and hits the expected breakpoint. locals is empty and there are no symbols for any variables. I believe I need to pass -gcflags="-N -l" to go build via dlv --build-flags.

I'm uncertain of the best way to achieve that when the entry point is DlvDebug

:DlvDebug --build-flags="-gcflags\"-N -l\"" -- inferior args doesn't get it done. Niether do a variety of attempts at escape fiddling.

Is there an example I have missed or what should I be doing instead ?

**Comment by robinbryce** [comment]
Hmm, I can't get this to work by using dlv directly, so I need to take this elsewhere. But the following 

DlvDebug --build-flags="-gcflags='-N -l'" -- findfiles .

Is the right rune to get the flags through from vim-delve

**Comment by sebdah** [comment]
Sure! That looks right and I just cross-checked in the code that we pass the flags on to `dlv` and that seems correct too. Best of luck!

**Comment by sebdah** [comment]
Closing this for now, please reopen if needed.
