### ISSUE TITLE
osx M1 chip delve fails to run in terminal 

### ISSUE THREAD

**Issue by ehrktia** [sebdah/vim-delve#56]
when trying to run `:DlvTest` from nvim in osx it fails with below message.
`native backend disabled during compilation`

details :
osx : mac os Monteray 12.4
chipset : M1
 go version : 
`go version go1.17.8 darwin/arm64`
dlv version : 
```
Delve Debugger
Version: 1.8.3
Build: ac81269eef6743ac8914acd32358dbe79c79340f
```
nvim version
```
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@Mac-1650023513425.local
```
lua settings for the plugin : 

`vim.g['delve_backend']='native'`

please let me know if you require more details.

**Comment by sebdah** [comment]
This seems like an issue in how either Neovim or Delve has been compiled on the machine. It's not coming from this plugin.
